[profile.release]
panic = "unwind"

[workspace]
members = [
    "primitives/core",
    "primitives/ethereum",
    "primitives/testutils",
    "pallets/bridge",
    "pallets/assets",
    "pallets/verifier",
    "pallets/verifier-lightclient",
    "pallets/eth-app",
    "pallets/erc20-app",
    "pallets/commitments",
    "node",
    "runtime",
]
